# Generated by Django 4.2.25 on 2025-10-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certificates/')),
                ('issued_at', models.DateField()),
                ('expires_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Зачислен'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершён'), ('FAILED', 'Не завершён')], default='ENROLLED', max_length=20)),
                ('enrolled_at', models.DateField(auto_now_add=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OfficerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('DIPLOMA', 'Диплом'), ('CERTIFICATE', 'Сертификат'), ('OTHER', 'Прочее')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='officer_docs/')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('issued_at', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('result', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
