# Generated by Django 4.2.25 on 2025-10-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('officers', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='positionhistory',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_history', to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='positionhistory',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.position'),
        ),
        migrations.AddField(
            model_name='officerdocument',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.trainingcourse'),
        ),
        migrations.AddField(
            model_name='courseenrollment',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.trainingcourse'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='users.officerprofile'),
        ),
        migrations.AddConstraint(
            model_name='courseenrollment',
            constraint=models.UniqueConstraint(fields=('officer', 'course'), name='uniq_enrollment_officer_course'),
        ),
    ]
