# Generated by Django 4.2.25 on 2025-10-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officers', '0003_alter_courseenrollment_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerdocument',
            name='document_type',
            field=models.CharField(choices=[('DIPLOMA', 'Диплом'), ('CERTIFICATE', 'Сертификат'), ('OFFICER_ID', 'Удостоверение офицера'), ('PERSONAL_ID', 'Удостоверение личности'), ('PASSPORT', 'Паспорт'), ('DRIVING_LICENSE', 'Водительское удостоверение'), ('MARRIAGE_CERT', 'Свидетельство о браке'), ('CHILD_BIRTH_CERT', 'Свидетельство о рождении ребёнка'), ('OTHER', 'Прочее')], max_length=20),
        ),
    ]
