# Generated by Django 4.2.25 on 2025-10-03 21:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', django_fsm.FSMField(default='draft', max_length=50, protected=True)),
                ('decision_chain', models.JSONField(default=list)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('gaps', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_from', models.DateField()),
                ('open_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Открыта'), ('IN_PROGRESS', 'В работе'), ('CLOSED', 'Закрыта')], default='OPEN', max_length=20)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.position')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.unit')),
            ],
        ),
    ]
