# Generated by Django 4.2.25 on 2025-10-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('staffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatematch',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='candidatematch',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='staffing.vacancy'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffing.vacancy'),
        ),
        migrations.AddIndex(
            model_name='vacancy',
            index=models.Index(fields=['status'], name='staffing_va_status_8fdf57_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidatematch',
            unique_together={('vacancy', 'officer')},
        ),
    ]
