# Generated by Django 4.2.25 on 2025-10-03 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('assessments', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rater',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback360',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_360', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='feedback360',
            name='rater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.rater'),
        ),
        migrations.AddField(
            model_name='competencyrating',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.competency'),
        ),
        migrations.AddField(
            model_name='competencyrating',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_ratings', to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.assessment'),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.competency'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessment',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.officerprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='competencyrating',
            unique_together={('officer', 'competency', 'source', 'assessed_at')},
        ),
    ]
