# Generated by Django 4.2.25 on 2025-10-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_competencyrequirement_competency_and_more'),
        ('assessments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitem',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.competency'),
        ),
        migrations.AlterField(
            model_name='competencyrating',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.competency'),
        ),
    ]
