# Generated by Django 4.2.25 on 2025-10-11 16:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='combat_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='combat_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='ИИН должен содержать 12 цифр')]),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'холост/не замужем'), ('MARRIED', 'женат/замужем'), ('DIVORCED', 'разведён/разведена'), ('WIDOWED', 'вдова/вдовец')], max_length=16),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='officers/photos/'),
        ),
        migrations.CreateModel(
            name='OfficerLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('BASIC', 'со словарём'), ('INTERMEDIATE', 'средний'), ('ADVANCED', 'свободно')], default='BASIC', max_length=16)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='users.officerprofile')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('officer', 'language')},
            },
        ),
    ]
