# Generated by Django 4.2.25 on 2025-10-13 12:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
        ('users', '0002_officerprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commanderprofile',
            name='appointed_at',
            field=models.DateField(blank=True, help_text='Дата назначения командиром', null=True),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='combat_notes',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='combat_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='command_scope',
            field=models.CharField(blank=True, choices=[('PLATOON', 'взвод'), ('COMPANY', 'рота'), ('BATTALION', 'батальон'), ('REGIMENT', 'полк'), ('BRIGADE', 'бригада'), ('DIVISION', 'дивизия'), ('OTHER', 'другое')], max_length=16),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='command_title',
            field=models.CharField(blank=True, help_text='Должность по командованию', max_length=128),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='current_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='directory.position'),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='iin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{12}$', message='ИИН должен содержать 12 цифр')]),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'холост/не замужем'), ('MARRIED', 'женат/замужем'), ('DIVORCED', 'разведён/разведена'), ('WIDOWED', 'вдова/вдовец')], max_length=16),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='nationality',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.rank'),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='relieved_at',
            field=models.DateField(blank=True, help_text='Дата освобождения от должности', null=True),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='staff_position',
            field=models.BooleanField(default=False, help_text='Штабная должность'),
        ),
        migrations.AddField(
            model_name='commanderprofile',
            name='subordinates_expected',
            field=models.PositiveIntegerField(default=0, help_text='Плановая численность подчинённых'),
        ),
        migrations.AlterField(
            model_name='commanderprofile',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='directory.unit'),
        ),
        migrations.AlterField(
            model_name='commanderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/photos/'),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='service_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CommanderLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=64)),
                ('level', models.CharField(choices=[('BASIC', 'со словарём'), ('INTERMEDIATE', 'средний'), ('ADVANCED', 'свободно')], default='BASIC', max_length=16)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='users.commanderprofile')),
            ],
            options={
                'ordering': ['language'],
                'unique_together': {('commander', 'language')},
            },
        ),
    ]
