# Generated by Django 4.2.25 on 2025-10-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_commanderprofile_appointed_at_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='commanderassignment',
            index=models.Index(fields=['commander', 'officer'], name='users_comma_command_4f7c7d_idx'),
        ),
        migrations.AddIndex(
            model_name='commanderassignment',
            index=models.Index(fields=['since', 'until'], name='users_comma_since_33c1ce_idx'),
        ),
    ]
