# Generated by Django 4.2.25 on 2025-10-17 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_commanderassignment_users_comma_command_4f7c7d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderassignment',
            name='since',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
