# Generated by Django 4.2.25 on 2025-10-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_competencyrequirement_competency_and_more'),
        ('users', '0005_alter_commanderassignment_since'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commanderprofile',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.rank'),
        ),
        migrations.AlterField(
            model_name='commanderprofile',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.unit'),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='rank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.rank'),
        ),
        migrations.AlterField(
            model_name='officerprofile',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.unit'),
        ),
    ]
