# Generated by Django 4.2.25 on 2025-10-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_commanderprofile_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerprofile',
            name='awards',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='children_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='education_civil',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='education_military',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='penalties',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='personal_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='rank_assignment_info',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='officerprofile',
            name='service_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
