# Generated by Django 4.2.25 on 2025-10-14 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
        ('users', '0004_commanderassignment_users_comma_command_4f7c7d_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('OFFICER', 'Офицер'), ('UNIT', 'Подразделение')], default='OFFICER', max_length=16)),
                ('is_collective', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'На утверждении'), ('APPROVED', 'Утверждено'), ('REJECTED', 'Отклонено'), ('EXECUTED', 'Исполнено (приказ)'), ('REVOKED', 'Отменено')], db_index=True, default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sanction_type', models.CharField(choices=[('REMARK', 'Замечание'), ('REPRIMAND', 'Выговор'), ('SEVERE_REPRIMAND', 'Строгий выговор'), ('WARNING_INCOMPETENCE', 'Предупреждение о неполном служебном соответствии'), ('DENY_LEAVE', 'Лишение очередного увольнения'), ('DEMOTION_POSITION', 'Снижение в должности'), ('DEMOTION_RANK', 'Снижение в звании'), ('DISCIPLINARY_ARREST', 'Дисциплинарный арест'), ('DISMISSAL', 'Увольнение по отрицательным мотивам')], max_length=32)),
                ('lifted_at', models.DateField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_initiated', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.officerprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('OFFICER', 'Офицер'), ('UNIT', 'Подразделение')], default='OFFICER', max_length=16)),
                ('is_collective', models.BooleanField(default=False)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('SUBMITTED', 'На утверждении'), ('APPROVED', 'Утверждено'), ('REJECTED', 'Отклонено'), ('EXECUTED', 'Исполнено (приказ)'), ('REVOKED', 'Отменено')], db_index=True, default='DRAFT', max_length=16)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_comment', models.TextField(blank=True)),
                ('order_number', models.CharField(blank=True, max_length=64)),
                ('order_date', models.DateField(blank=True, null=True)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reward_type', models.CharField(choices=[('THANKS', 'Благодарность'), ('LIFT_SANCTION', 'Досрочное снятие взыскания'), ('CERTIFICATE', 'Грамота'), ('GIFT', 'Ценный подарок'), ('EARLY_RANK', 'Досрочное присвоение звания'), ('HONOR_BOARD', 'Доска почёта / Книга отличников'), ('STATE_AWARD', 'Гос./ведомственная награда'), ('EXTRA_VACATION', 'Отпуск вне очереди / доп. отдых'), ('DISCHARGE_THANKS', 'Поощрительное увольнение в запас')], max_length=32)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_initiated', to=settings.AUTH_USER_MODEL)),
                ('linked_sanction', models.ForeignKey(blank=True, help_text='Для досрочного снятия взыскания', null=True, on_delete=django.db.models.deletion.SET_NULL, to='discipline.sanction')),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='users.officerprofile')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='directory.unit')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['officer', 'status'], name='discipline__officer_5f446e_idx'),
        ),
        migrations.AddIndex(
            model_name='sanction',
            index=models.Index(fields=['sanction_type', 'status'], name='discipline__sanctio_500337_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['officer', 'status'], name='discipline__officer_d6582c_idx'),
        ),
        migrations.AddIndex(
            model_name='reward',
            index=models.Index(fields=['reward_type', 'status'], name='discipline__reward__584a19_idx'),
        ),
    ]
