# Generated by Django 4.2.25 on 2025-10-22 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_initiated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sanction',
            name='initiator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_initiated', to=settings.AUTH_USER_MODEL),
        ),
    ]
