# Generated by Django 4.2.25 on 2025-10-22 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencyrequirement',
            name='competency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.competency'),
        ),
        migrations.AlterField(
            model_name='position',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.unit'),
        ),
        migrations.AlterField(
            model_name='positionrequirement',
            name='min_rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.rank'),
        ),
        migrations.AlterField(
            model_name='trainingcourse',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directory.provider'),
        ),
    ]
