# Generated by Django 4.2.25 on 2025-12-22 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0002_alter_competencyrequirement_competency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('EDUCATION', 'Образование'), ('EXPERIENCE', 'Опыт службы'), ('FUNCTIONS', 'Функциональные обязанности'), ('COMPETENCY', 'Компетенции')], max_length=32)),
                ('text', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('source', models.CharField(blank=True, help_text='Источник (приказ, пункт, год)', max_length=255)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='directory.position')),
            ],
            options={
                'ordering': ['category', 'order'],
                'indexes': [models.Index(fields=['position', 'category'], name='directory_p_positio_ef4aa8_idx')],
            },
        ),
    ]
