# Generated by Django 4.2.25 on 2025-12-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0003_positionqualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('unit', 'code')},
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['unit', 'code'], name='directory_p_unit_id_75cb95_idx'),
        ),
    ]
