# Generated by Django 4.2.25 on 2025-10-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0001_initial'),
        ('users', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='planstep',
            name='trajectory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='career.careertrajectory'),
        ),
        migrations.AddField(
            model_name='careertrajectory',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajectories', to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='careertrajectory',
            name='target_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.position'),
        ),
        migrations.AddIndex(
            model_name='planstep',
            index=models.Index(fields=['due_date'], name='career_plan_due_dat_4f7337_idx'),
        ),
        migrations.AddIndex(
            model_name='careertrajectory',
            index=models.Index(fields=['status'], name='career_care_status_686eea_idx'),
        ),
    ]
