# Generated by Django 4.2.25 on 2025-10-03 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('insights', '0001_initial'),
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajectoryforecast',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.officerprofile'),
        ),
        migrations.AddField(
            model_name='trajectoryforecast',
            name='target_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='directory.position'),
        ),
    ]
